// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
//require('dotenv').config()
const {getCLIConnectionString} = require('./lib/getConnectionString')

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url:  getCLIConnectionString(process.env.NODE_ENV),
  },
});
